
import json

# Response Models
from PythonWebSocketsGame.Application.Responses.Models.PlayersModelResponse import PlayersModelResponse
from PythonWebSocketsGame.Application.Responses.Models.AwaitingPlayersModelResponse import AwaitingPlayersModelResponse
from PythonWebSocketsGame.Application.Responses.Models.ServerStateModelResponse import ServerStateModelResponse
from PythonWebSocketsGame.Application.Responses.Models.ClientDetailsModelResponse import ClientDetailsModelResponse


# Ws Response Wrappers
from PythonWebSocketsGame.Application.Responses.WebSocketResponses.WsNewGameResponse import WsNewGameResponse
from PythonWebSocketsGame.Application.Responses.WebSocketResponses.WsServerStateResponse import WsServerStateResponse
from PythonWebSocketsGame.Application.Responses.WebSocketResponses.WsClientResponse import WsClientResponse

class WsGameNotification:
